"""
This type stub file was generated by pyright.
"""

np = ...
FILE_IDENTIFIER_LENGTH = ...

def Get(packer_type, buf, head):
    """Get decodes a value at buf[head] using `packer_type`."""
    ...

def GetVectorAsNumpy(numpy_type, buf, count, offset):  # -> NDArray[float64]:
    """GetVecAsNumpy decodes values starting at buf[head] as
    `numpy_type`, where `numpy_type` is a numpy dtype."""
    ...

def Write(packer_type, buf, head, n):  # -> None:
    """Write encodes `n` at buf[head] using `packer_type`."""
    ...
