"""
This type stub file was generated by pyright.
"""

def GetSizePrefix(buf, offset):  # -> Any:
    """Extract the size prefix from a buffer."""
    ...

def GetBufferIdentifier(buf, offset, size_prefixed=...):
    """Extract the file_identifier from a buffer"""
    ...

def BufferHasIdentifier(buf, offset, file_identifier, size_prefixed=...): ...
def RemoveSizePrefix(buf, offset):  # -> tuple[Any, Any]:
    """
    Create a slice of a size-prefixed buffer that has
    its position advanced just past the size prefix.
    """
    ...
